# Software R
\newpage

## Introdução
```{r, include=FALSE}
knitr::opts_chunk$set(tidy=FALSE, message = FALSE,warning =  FALSE,fig.align = "center",fig.show = "hold")
```
O presente trabalho foi elaborado tendo como apoio na análise dos dados a linguagem de programação R^[O seu criador é tido como John Chambers, no ano de 1976, nos laboratórios Bell sediados nos Estados Unidos], sendo por isso fundamental uma breve descrição da mesma, assim como a apresentação e descrição dos principais pacotes utilizados, sendo também o objectivo a aplicabilidade de ferramentas de computação na análise de dados.

O R é uma linguagem de programação *open source* bastante utilizada para computação estatística, havendo uma grande comunidade de suporte à linguagem, assim como uma grande  diversidade de pacotes de software para várias áreas de matemática e estatística aplicada, sendo bastante utilizada em *data mining* e *machine learning*. A capacidade do R deve-se em grande parte a extensão dada à linguagem através dos pacotes desenvolvidos pela comunidade R, sendo *open source*, que desta forma vão dando resposta aos desafios presentes na resolução de problemas estatísticos e na análise de dados, tornando esta linguagem de fácil utilização , não sendo necessário grandes conhecimentos de programação para aplicar esses modelos a casos práticos.

Desta forma, e havendo uma grande disponibilidade de pacotes desenvolvidos para o sector financeiro, optou-se pela sua utilização no desenvolvimento deste trabalho, sendo parte essencial para extração, tratamento e análise dos dados. Também foi parte basilar da construção do documento, sendo utilizado o BOOKDOWN, pacote para desenvolvimento e escrita de HTML, PDF, EPub e livros (@R-bookdown).

A versão utilizada no desenvolvimento do trabalho foi o R-4.0.3^[Disponível em "https://cran.r-project.org/bin/windows/base/"], sendo utilizado como IDE o RStudio versão 1.3.1093^[Disponível em "https://rstudio.com/products/rstudio/download/#download"]. O presente trabalho, o código R utilizado, assim como os dados analisados, encontram-se disponíveis no repositório *online* GitHub, em "https://github.com/lsbaptista/Thesis".

## Finanças e R
O R disponibiliza uma grande variedade de pacotes desenvolvidos pela sua comunidade. No entanto, devido a essa diversidade torna-se às vezes complicado saber qual o mais adequado para utilizar em cada uma das situações. A opção ao longo do trabalho prendeu-se essencialmente por optar por aqueles que deram uma melhor resposta ao problema em análise, havendo utilização de pacotes diferentes dentro de um mesmo tipo de análise, por de alguma forma um se adequar melhor que o outro, nem que fosse apenas na extração dos dados para posterior apresentação em tabelas. Salienta-se o facto de muitos destes pacotes dependerem de outros, sendo que ao serem instalados, essas dependências também são instaladas.Dito isto passo seguidamente a apresentar e descrever de forma sumaria os principais pacotes aplicados na análise e modelação dos dados.

### fGarch
O pacote *fGarch* faz parte da organização Rmetrics, sendo este um projecto de software de desenvolvimento livre para o ensino de finanças computacionais^[Disponível em "https://www.rmetrics.org/"]. O *fGarch* disponibiliza uma colecção de funções para analisar e modelar comportamento que apresentam heterocedasticidade em modelos de séries temporais (@fGarch).

Uma das funções utilizadas foi o *garchFit()*, que estima os parâmetros de um processo univariado ARMA-GARCH. Na função pode-se definir os parâmetros *p* e *q* relativos a ordem, sendo que GARCH(1,1) representa um modelo de primeira ordem. O tipo de distribuição dos dados pode ser escolhida de entre um grupo, sendo que o valor por defeito é o de uma distribuição normal. Vários valores podem ser extraidos, como um vector numérico dos resíduos ou dos respectivos desvio padrão calculados. Com a função *summary()* obtemos descrição estatística do modelo e podemos obter vários gráficos de interesse com a função *plot()*.

### fPortfolio
O pacote *fPortfolio* é mais um pacote de análise financeira disponibilizado pela Rmetrics, sendo que disponibiliza uma colecção de funções para optimizar portefólios a para analisa-los de diferentes pontos de vista (@fPortfolio).

Um dos métodos utilizados para a definição de portefólios foi o *minvariancePortfolio()* que retorna um portefólio com a mínima variância na fronteira eficiente, minimizando o risco. Nesta função pode-se definir as restrições impostas na definição do portefólio, como a possibilidade de vendas a descoberto.

Este pacote apresenta depêndencias com outros, designadamente *fBasics*, pacote desenvolvido pela Rmetrics tendo como finalidade disponibilizar funções gerais de análise estatística para o sector financeiro, como estimação de parâmetros, testes de hipótese e várias funções para distribuições de retornos financeiros como a Distribuição Hiperbólica Generalizada (@fBasics), o *MFTSR*, pacote para modelar series temporais financeiras sendo parte integrante do livro "*Modelling Financial Time Series with R*" (@MFTSR). Uma das funções utilizadas foi a do cálculo do *EWMA*, utilizando o ewmaVol() e o *fAssets*, pacote desenvolvido pela Rmetrics, que providência uma colecção de funções para gerir, investigar e analisar um conjunto de dados de activos financeiros (@fAssets).

### Portes
Pacote que contem univariados e multivariados *portmanteau* testes estatísticos de series temporais baseados em distribuição assintótica e em testes de significância de Monte Carlo (@portes). Um dos testes *portmanteau* utilizados foi o teste Ljun-Box para testar a autocorrelação. Estes testes são bastante úteis ao trabalhar com modelos ARIMA. 

Este pacote tem como uma das depêndencias o pacote *forecast* que contêm métodos e ferramentas para analisar e prever series temporais univariadas como modelos automáticos ARIMA.

### RQuantLib
O *RQuantLib* é desenvolvido pelo QuantLib, sendo uma biblioteca de código aberto para finanças quantitativas (@RQuantLib). A função utilizada foi a *EuropeanOptionImpliedVolatility()* para cálculo da volatilidade implícita nas opções em análise.

### Rugarch
*Rugarch* é um pacote que contêm uma grande variedade de modelos unívariados GARCH, com métodos para simulação, inferência e criar gráficos (@rugarch). Neste caso foi utilizada a função *ugarchspec()* para utilizar o método eGARCH, que fornecia uma melhor resposta no modelo em análise do que utilizando o modelo generalista GARCH. Este modelo disponibiliza toda a informação estatística necessária para validar o modelo e seus pressupostos, sendo que comparativamente com o pacote fGarch, permite aplicação de outros modelos GARCH.

### Tidyquant
O pacote *Tidyquant* é uma colecção de outros pacotes financeiros, fornecendo, deste modo, de uma só vez, vários pacotes utilizados para o sector financeiro e de gestão (@tidyquant). Temos o  *PerformanceAnalytics* sendo uma colecção de funções econométricas para performance e análise de risco (@PerformanceAnalytics). Uma das funções utilizadas foi a do *VaR()*, permitindo definir o tipo de método a aplicar no cálculo do *Value at Risk*. O *quantmod* é uma *framework* para modelos de finanças quantitativas, contendo funções para aceder  a várias *api* para obter dados de cotações, como no yahoo finance, assim como para o cálculo de retornos e visualização dos dados (@quantmod). O *TTR* providencia uma colecção de mais de 50 indicadores técnicos para criar regras de *trading* (@TTR). Outros pacotes, como o *lubridate*, contêm funções para lidar com datas e tempos, o *zoo* utilizado para series temporais regulares e irregulares e o pacote *xts* para lidar com *timestamps* em series temporais.














