--- 
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
     extra_dependencies: ["flafter"]
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
classoption: openany
mainfont: Arial
fontsize: 12pt
linestretch: 1.5
geometry: "left=3.5cm,right=2cm,top=3cm,bottom=3cm, asymmetric"
indent: true
header-includes:
  - \usepackage{indentfirst}
  - \usepackage{floatrow}
  - \floatsetup[figure]{capposition=top}
  - \floatsetup[table]{capposition=top}
  - \usepackage{subfig}
pagestyle: plain
papersize: a4
toc: true
toc-depth: 2
toc-title: Índice
lof:  True
lot: True
---

# Simbologia e notações{.unnumbered}

ACF - Função de auto-correlação; \

ARMA - Auto-regressivo de médias móveis; \

ARCH - Heteroscedasticidade condicional auto-regressiva; \

CMP - Reta do mercado capital; \

DEaR - Daily Value at Risk; \

EWMA - Média móvel exponencial ponderada  (EWMA); \

EGARCH - Heteroscedasticidade condicional auto-regressiva generalizada exponencial; \

GARCH - Heteroscedasticidade condicional auto-regressiva generalizada ; \

i.i.d - independente e identicamente distribuída; \

K - Preço de exercício da opção; \

MAE - Erro absoluto médio; \

MSE - Erro quadrático médio; \

RMSE - Desvio padrão empírico (amostral) generalizado; \

r - Retorno; \

$r_j$ - Taxa de juro sem risco; \

S - Valor do activo; \

VaR - Value at Risk; \

VI - Volatilidade Implícita; \

X - Fracção investida no activo; \

$\mu$ - Média; \

$\sigma$ - Desvio padrão; \

$\sigma^2$ - Variância; \

$\sigma_{ij}$ - Covariância; \

$\varepsilon$ - variável com distribuição normal N(0,1); \

$\phi$ - Parâmetros do modelo AR; \

$\theta$ - Parâmetros do modelo MA; \

$\mathcal{V}$ - Taxa de variância de longo prazo; \

$\gamma\ \alpha\ \beta$ - Pesos atribuídos no modelo GARCH; \

$\omega$ - o mesmo que $\gamma\mathcal{V}$; \

$\rho$ - Correlação; \

$\zeta_1$ - Valor da assimetria; \

$\zeta_2$ - Valor do excesso de curtose; \










\mainmatter 
